version: "2"

services:
  myplant:
    image: 'docker-spring-boot-postgres:latest'
    build: backend/myplant/
    container_name: myplant
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  frontend:
    build: frontend/
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - myplant

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
